name: "pytest"

on:
  push:
    branches:
      - main
    paths:
      - "services/**"
      - "!services/docs/**"
      - "!services/mkdocs.yml"
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "services/**"
      - "!services/docs/**"
      - "!services/mkdocs.yml"

permissions:
  contents: read
  checks: write
  pull-requests: write

defaults:
  run:
    working-directory: ./services

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: ./.github/composite/setup-python
        with:
          uv_version: "0.5.5"
          working_dir: services

      - name: Download ckpt file from huggingface-hub
        shell: bash
        run: uv run huggingface-cli download khokao/synergetica base.ckpt --local-dir src/api/generator/checkpoints/

      - name: pytest
        run: | # set -o pipefail is required to propagate pytest exit code
          set -o pipefail
          uv run pytest --junitxml=pytest.xml | tee pytest-coverage.txt

      # When pytest fails, this step will still run to comment on the PR
      - name: Pytest coverage comment
        if: always() && github.event_name == 'pull_request'
        uses: MishaKav/pytest-coverage-comment@main
        with:
          # This is a workaround for the following.
          # issue: https://github.com/MishaKav/pytest-coverage-comment/issues/161
          pytest-coverage-path: services/pytest-coverage.txt
          junitxml-path: services/pytest.xml

      - name: Upload pytest coverage
        uses: actions/upload-artifact@v4
        with:
          name: pytest-coverage
          path: pytest-coverage.txt
